spring.application.name=gateway-resilience

server.port=8080

# ===============================
# Gateway Route Configuration
# ===============================
spring.cloud.gateway.routes[0].id=example_route
spring.cloud.gateway.routes[0].uri=http://example.org
spring.cloud.gateway.routes[0].predicates[0]=Path=/example/**

# ===============================
# Resilience4j Circuit Breaker
# ===============================
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.failureRateThreshold=50

logging.level.org.springframework.cloud.gateway=INFO
logging.level.com.cognizant.gateway=DEBUG
